FROM aifraenkel/jenkins-preconf-apis:v1
LABEL maintainer=”aifraenkel@gmail.com”

USER root

# Setup Jenkins - Create Jenkins Log Folder
RUN mkdir /shared
RUN mkdir /shared/certs
# COPY xxx.crt /shared/certs
# COPY xxx.key /shared/certs
# COPY xxx_ca.crt /shared/certs


